doctrine:
    dbal:
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
            report_type_enum: App\Doctrine\DBAL\Types\ReportTypeType
            financing_enum: App\Doctrine\DBAL\Types\FinancingType
        driver:   pdo_mysql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
        charset:  UTF8
        server_version: '%mysql_version%'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            App:
                type: annotation
                prefix: App\Entity
                dir: '%kernel.project_dir%/src/Entity'
                is_bundle: false

doctrine_migrations:
    namespace: App\Migrations
    dir_name: '%kernel.project_dir%/src/Migrations'

parameters:
    env(DATABASE_HOST): mysql
    env(DATABASE_PORT): 3306
    env(DATABASE_USER): db
    env(DATABASE_NAME): db
    env(DATABASE_PASSWORD): db
    mysql_version: 10.1.23-MariaDB-1~jessie

services:
    Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'
