hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type:                google
            client_id:           '%env(GOOGLE_OAUTH_ID)%'
            client_secret:       '%env(GOOGLE_OAUTH_SECRET)%'
            scope:                "email profile"
        vkontakte:
            type:                vkontakte
            client_id:           '%env(VKONTAKTE_OAUTH_ID)%'
            client_secret:       '%env(VKONTAKTE_OAUTH_SECRET)%'
            authorization_url:   'https://oauth.vk.com/authorize?v=3.0'
            access_token_url:    'https://oauth.vk.com/access_token?v=3.0'
            infos_url:           'https://api.vk.com/method/users.get?v=3.0'

    connect:
        confirmation: false

services:
    hwi_oauth.account.connector: '@App\Security\Oauth2UserProvider'

parameters:
    env(GOOGLE_OAUTH_ID): null
    env(GOOGLE_OAUTH_SECRET): null
    env(VKONTAKTE_OAUTH_ID): null
    env(VKONTAKTE_OAUTH_SECRET): null
