hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type:                google
            client_id:           '%env(GOOGLE_OAUTH_ID)%'
            client_secret:       '%env(GOOGLE_OAUTH_SECRET)%'
            scope:                "email profile"
        vkontakte:
            type:                vkontakte
            client_id:           '%env(VKONTAKTE_OAUTH_ID)%'
            client_secret:       '%env(VKONTAKTE_OAUTH_SECRET)%'
    fosub:
        properties: '%hwi_oauth.fosub.properties%'

    connect:
        confirmation: false

parameters:
    env(GOOGLE_OAUTH_ID): null
    env(GOOGLE_OAUTH_SECRET): null
    env(VKONTAKTE_OAUTH_ID): null
    env(VKONTAKTE_OAUTH_SECRET): null
    hwi_oauth.fosub.properties:
        google: googleId
        vkontakte: vkontakteId
