services:
    _defaults:
        public: false
        autowire: by_id

    number.formatter:
        class: NumberFormatter
        autowire: false
        arguments:
            - '%locale%'
            - !php/const:NumberFormatter::CURRENCY

    Money\Currencies\ISOCurrencies: ~

    Money\Formatter\IntlMoneyFormatter: ~
    Money\Formatter\DecimalMoneyFormatter: ~
    Money\MoneyFormatter:
        alias: Money\Formatter\IntlMoneyFormatter

    Money\Exchange\SwapExchange: ~
    Money\Converter: ~
    Exchanger\Service\Google: ~
    Swap\Swap: ~
