parameters:
    env(SENTRY_DSN): null

sentry:
    dsn: "%env(SENTRY_DSN)%"
#    release: '%env(APP_VERSION)%'
    environment: '%kernel.environment%'
    app_path: '%env(APP_DIR)%'
    skip_capture:
        - 'Symfony\Component\HttpKernel\Exception\HttpExceptionInterface'
        - 'Symfony\Component\Security\\Core\Exception\AccessDeniedException'
    options:
        processors:
            - 'Raven_Processor_SanitizeDataProcessor'
