parameters:
    env(SENTRY_DSN): null
    env(APP_DIR): '%kernel.project_dir%'

sentry:
    dsn: "%env(SENTRY_DSN)%"
    skip_capture:
        - 'Symfony\Component\HttpKernel\Exception\HttpExceptionInterface'
        - 'Symfony\Component\Security\\Core\Exception\AccessDeniedException'
    options:
        processors:
            - 'Raven_Processor_SanitizeDataProcessor'
        app_path: '%env(APP_DIR)%'
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'
