stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            tree:           false
            timestampable:  true
            blameable:      false
            sluggable:      true
            translatable:   false
            loggable:       false
            softdeleteable: false
            uploadable:     false
