twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        '%kernel.project_dir%/templates': null
        '%kernel.project_dir%/templates/FOSUser': FOSUser
    form_themes:
         - 'bootstrap_3_horizontal_layout.html.twig'
#        - 'bootstrap_3_layout.html.twig'

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
