pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER} .
      - docker network create DRONE_ASTRA50_${DRONE_BUILD_NUMBER}
      - >-
        docker run -d --name DRONE_ASTRA50_${DRONE_BUILD_NUMBER} --network DRONE_ASTRA50_${DRONE_BUILD_NUMBER}
        -e MYSQL_DATABASE="db"
        -e MYSQL_USER="user"
        -e MYSQL_PASSWORD="password"
        -e MYSQL_RANDOM_ROOT_PASSWORD='true'
        mariadb
      - docker run --rm --network DRONE_ASTRA50_${DRONE_BUILD_NUMBER} docker sh -c "while ! nc -z DRONE_ASTRA50_${DRONE_BUILD_NUMBER} 3306; do sleep 1; done"
      - >-
        (docker run --rm --network DRONE_ASTRA50_${DRONE_BUILD_NUMBER}
        -e SYMFONY_ENV=test
        -e SYMFONY_DEBUG=0
        -e DATABASE_HOST=DRONE_ASTRA50_${DRONE_BUILD_NUMBER}
        -e DATABASE_USER="user"
        -e DATABASE_PASSWORD="password"
        registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER}); local result=$?;
      - docker rm -f DRONE_ASTRA50_${DRONE_BUILD_NUMBER}
      - docker network rm DRONE_ASTRA50_${DRONE_BUILD_NUMBER}
      - >+
        if [ "$result" == 0 ]; then
          docker login -u"$HUB_LOGIN" -p"$HUB_PASSWORD" registry.gitlab.com
          docker push registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER} > /dev/null
          docker rmi --force `docker images -q --filter "before=registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER}" registry.gitlab.com/astra50/astra50.ru` || true
        else
          docker rmi --force registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER}
        fi
      - exit "$result"

  deploy:
    image: plugins/ssh
    host:
      - s2.automagistre.ru
      - s1.grachevko.ru
    user: premier
    port: 22
    script:
      - docker pull registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER} > /dev/null
      - docker service update --image registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER} astra50_app
      - docker rmi `docker images -q --filter "before=registry.gitlab.com/astra50/astra50.ru:${DRONE_BUILD_NUMBER}" registry.gitlab.com/astra50/astra50.ru` 2> /dev/null || true
    when:
      branch: master

  notify:
    image: plugins/slack
    channel: drone
    username: drone
