clone:
    git:
        image: plugins/git
        depth: 20

_docker: &docker
    image: docker
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ HUB_LOGIN, HUB_PASSWORD ]

_when_master: &when-master
    when:
        event: push
        branch: master
        status: success

pipeline:
    build app:
        <<: *docker
        group: build
        commands:
            - >-
                docker build -t "astra50/astra50:${DRONE_BUILD_NUMBER}"
                --label build=${DRONE_BUILD_NUMBER}
                --build-arg APP_VERSION="$DRONE_BUILD_NUMBER"
                --build-arg APP_BUILD_TIME="`date --rfc-2822`"
                .

    validate php-cs-fixer:
        group: validate
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - git diff-tree -r --name-only ${DRONE_PREV_COMMIT_SHA} master | grep -q -e "^.+\.php$" || exit 0
            - >-
                /docker-entrypoint.sh
                php-cs-fixer fix
                --config=./.php_cs.dist
                --verbose
                --dry-run
                --using-cache=no
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'
            MIGRATIONS: 'false'
        when:
            branch:
                exclude: [ master ]

    validate blank end line:
        group: validate
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - >-
                find . -type f -exec grep -Iq . {} \; -and -print0
                | xargs -0 -L1 bash -c 'test -z "$(tail -c 1 "$0")"
                || (echo "No new line at end of $0" && exit 1)'
                || exit 1
        when:
            branch:
                exclude: master

    validate phpstan:
        group: validate
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - git diff-tree -r --name-only ${DRONE_PREV_COMMIT_SHA} | grep -q -e "^.+\.php$" || exit 0
            - cd "$APP_DIR"
            - /docker-entrypoint.sh php -d memory_limit=-1 vendor/bin/phpstan analyse --level 6 --configuration phpstan.neon --no-progress src tests
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '1'
            MIGRATIONS: 'false'
        when:
            branch:
                exclude: master

    validate symfony requirements:
        group: validate
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - /docker-entrypoint.sh requirements-checker
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'
            MIGRATIONS: 'false'
        when:
            branch:
                exclude: [ master ]

    validate symfony security:
        group: validate
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - git diff-tree -r --name-only ${DRONE_PREV_COMMIT_SHA} | grep -q composer.lock || exit 0
            - /docker-entrypoint.sh security-checker security:check $APP_DIR/composer.lock
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'
            MIGRATIONS: 'false'
        when:
            branch:
                exclude: [ master ]

    validate doctrine: &validate-doctrine
        group: validate
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - /docker-entrypoint.sh console doctrine:schema:validate
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'
            MIGRATIONS: 'true'
            WAIT_HOSTS: 'mysql:3306'

    test phpunit: &test-phpunit
        group: test
        image: astra50/astra50:${DRONE_BUILD_NUMBER}
        commands:
            - cd "$APP_DIR"
            - /docker-entrypoint.sh phpunit
        environment:
            APP_ENV: 'test'
            APP_DEBUG: '0'
            FIXTURES: 'true'
            MIGRATIONS: 'false'

    publish:
        <<: *docker
        <<: *when-master
        group: publish
        commands:
            - docker login -u"$HUB_LOGIN" -p"$HUB_PASSWORD"
            - docker push "astra50/astra50:${DRONE_BUILD_NUMBER}" > /dev/null

    clean:
        <<: *docker
        group: deploy
        commands:
            - docker rmi --force `docker images --filter before=astra50/astra50:${DRONE_BUILD_NUMBER} --format "{{ .Repository }}:{{ .Tag }}" astra50/astra50`
        when:
            branch: master
            status: [ success, failure ]

    deploy: &deploy_service
        <<: *docker
        <<: *when-master
        commands:
            - docker service update --detach=false --image "astra50/astra50:${DRONE_BUILD_NUMBER}" astra50

services:
    mysql:
        image: mariadb:10.1.23
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'db'
            MYSQL_PASSWORD: 'db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        tmpfs:
            - /var/lib/mysql
