version: '3.4'

services:
    app:
#        build:
#            context: .
#            args:
#                SOURCE_DIR: ./var/null
        image: astra50/app:dev
        hostname: astra50.local
        volumes:
            - ./:/usr/local/app
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            XDEBUG: 'true'
            OPCACHE: 'false'
            MIGRATIONS: 'false'
            WAIT_HOSTS: 'mysql:3306'

    mysql:
        image: mariadb:10.1.23
        hostname: mysql.astra50.local
        volumes:
            - mysql-db:/var/lib/mysql
            - ./:/usr/local/app
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

volumes:
    mysql-db:
        driver: local
        driver_opts:
            device: tmpfs
            type: tmpfs
            o: size=512m
