FROM php:fpm-alpine

MAINTAINER Konstantin Grachev <ko@grachev.io>

ENV APP_DIR=/usr/local/app
ENV \
    PATH=${APP_DIR}/bin:${PATH} \
    COMPOSER_BIN_DIR=/usr/local/bin \
    COMPOSER_CACHE_DIR=/var/cache/composer \
    COMPOSER_ALLOW_SUPERUSER=1

WORKDIR ${APP_DIR}

RUN set -ex \
    && apk add --no-cache \
        icu-dev \
        zlib-dev \
    && docker-php-ext-install zip intl pdo_mysql iconv \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer global require phpunit/phpunit \
    && rm -rf ${COMPOSER_CACHE_DIR}/*

RUN set -ex \
    && apk add --no-cache git openssh-client mysql-client \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && { \
        echo 'xdebug.remote_enable=On'; \
        echo 'xdebug.remote_autostart=On'; \
        echo 'xdebug.remote_connect_back=On'; \
    } >> ${PHP_INI_DIR}/conf.d/xdebug.ini \
    && apk del .build-deps

RUN set -ex \
    && ln -s $APP_DIR/bin/console /usr/local/bin/sf \
    && { \
        echo '#!/bin/sh'; \
        echo 'set -ex'; \
        echo 'while ! nc -z mysql 3306; do sleep 1; done'; \
        echo 'composer run-script build-parameters'; \
        echo 'exec "$@"'; \
    } > /usr/local/bin/docker-entrypoint.sh \
    && chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php", "bin/console", "server:run", "0.0.0.0:80"]
