login_check:
    path:   /login_check
    methods: [ 'POST' ]

logout:
    path: /logout

homepage:
    path: /

contacts:
    path: /contacts
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/contacts.html.twig
