services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\DataFixtures\FixtureInterface:
            tags:
                - { name: 'doctrine.fixture.orm' }

    App\DataFixtures\:
        resource: '%kernel.project_dir%/src/DataFixtures'
