services:
    app.controller.base:
        class: AppBundle\Controller\Controller
        calls:
            - ['setContainer', ['@service_container']]

    app.controller.news:
        class: AppBundle\Controller\NewsController
        parent: app.controller.base
        arguments:
            - '@app.repository.news'

    app.controller.account:
        class: AppBundle\Controller\AccountController
        parent: app.controller.base
        arguments:
            - '@app.repository.user'

    app.controller.area:
        class: AppBundle\Controller\AreaController
        parent: app.controller.base
        arguments:
            - '@app.repository.area'
