services:
    app.controller.base:
        class: AppBundle\Controller\Controller
        calls:
            - ['setContainer', ['@service_container']]

    app.controller.news:
        class: AppBundle\Controller\NewsController
        parent: app.controller.base
        arguments:
            - '@app.repository.news'
