services:
    app.form.registration_type:
        class: AppBundle\Form\Type\RegistrationFormType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: fos_user_registration }

    app.form.account_type:
        class: AppBundle\Form\Type\AccountType
        tags:
            - { name: form.type }
