services:
    app.listener.payment_new:
        class: AppBundle\EventDispatcher\Payment\NewPaymentTypeListener
        arguments:
            - '@app.repository.area'
            - '@app.repository.payment'
        tags:
            - { name: kernel.event_subscriber }
