services:
    app.menu.builder:
        class: AppBundle\Menu\Builder
        arguments:
            - '@knp_menu.factory'
            - '@security.authorization_checker'
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createManagerMenu, alias: manager }
