services:
    app.menu.builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
