services:
    app.doctrine.entity_repository:
        class: AppBundle\Doctrine\EntityRepository
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    app.repository.news:
        class: AppBundle\Entity\Repository\NewsRepository
        parent: app.doctrine.entity_repository

    app.repository.user:
        class: AppBundle\Entity\Repository\UserRepository
        parent: app.doctrine.entity_repository

    app.repository.area:
        class: AppBundle\Entity\Repository\AreaRepository
        parent: app.doctrine.entity_repository

    app.repository.payment_type:
        class: AppBundle\Entity\Repository\PurposeRepository
        parent: app.doctrine.entity_repository

    app.repository.payment:
        class: AppBundle\Entity\Repository\PaymentRepository
        parent: app.doctrine.entity_repository

    app.repository.street:
        class: AppBundle\Entity\Repository\StreetRepository
        parent: app.doctrine.entity_repository
