services:
    app.user.user_provider:
        class: AppBundle\User\UserProvider
        parent: hwi_oauth.user.provider.fosub_bridge

    hwi_oauth.account.connector:
        alias: app.user.user_provider
